import { PresenterId, ScriptLine, QAItem, LapbookComponent } from "./types";

export const presentersData = {
  [PresenterId.ANDI]: {
    id: PresenterId.ANDI,
    name: "Andi",
    role: "Presenter Pembuka & Pernyataan Umum",
    color: "from-sky-400 to-blue-600",
    shadowColor: "shadow-blue-500/20",
    bgColor: "bg-blue-50/50",
    borderColor: "border-blue-200",
    focus: "Membuka presentasi, menarik audiens dengan hook tak terduga, dan menyampaikan definisi awal secara klasifikasi ilmiah.",
  },
  [PresenterId.SINTA]: {
    id: PresenterId.SINTA,
    name: "Sinta",
    role: "Deskripsi Ciri Fisik",
    color: "from-pink-400 to-rose-600",
    shadowColor: "shadow-pink-500/20",
    bgColor: "bg-pink-50/50",
    borderColor: "border-pink-200",
    focus: "Menjelaskan detail anatomi tubuh belalang anggrek, warna kamuflase yang mirip bunga, dan kecepatan kaki raptorial.",
  },
  [PresenterId.RINA]: {
    id: PresenterId.RINA,
    name: "Rina",
    role: "Deskripsi Perilaku & Habitat",
    color: "from-emerald-400 to-green-600",
    shadowColor: "shadow-green-500/20",
    bgColor: "bg-green-50/50",
    borderColor: "border-green-200",
    focus: "Mengisahkan drama perburuan dengan storytelling, siklus makannya dengan roda pemutar, dan peta habitat hutan tropis beserta ancaman kepunahan.",
  },
  [PresenterId.BUDI]: {
    id: PresenterId.BUDI,
    name: "Budi",
    role: "Presenter Penutup & Moderator",
    color: "from-amber-400 to-orange-600",
    shadowColor: "shadow-orange-500/20",
    bgColor: "bg-orange-50/50",
    borderColor: "border-orange-200",
    focus: "Merangkum kesimpulan dengan suara tegas, menyampaikan pesan melestarikan alam Indonesia, serta memoderasi sesi tanya jawab.",
  },
};

export const scriptLines: ScriptLine[] = [
  // Bagian 1: Pembukaan (Andi)
  {
    id: "p1-1",
    timeCode: "0:00",
    timeInSeconds: 0,
    endTimeInSeconds: 10,
    speaker: PresenterId.ANDI,
    action: "Berdiri tegak di depan audiens, senyum percaya diri, tatap audiens secara menyeluruh, pegang lapbook tertutup di tangan kiri.",
    speech: "Assalamualaikum warahmatullahi wabarakatuh. Selamat pagi, Bapak/Ibu guru dan teman-teman sekalian.",
    technique: "Salam pembuka yang santun, kontak mata ke seluruh audiens, senyum hangat.",
  },
  {
    id: "p1-2",
    timeCode: "0:10",
    timeInSeconds: 10,
    endTimeInSeconds: 20,
    speaker: PresenterId.ANDI,
    action: "Buka lapbook perlahan, tunjuk banner judul di tengah atas lapbook.",
    speech: "Perkenalkan, kami dari Kelompok 3, Kelas X-A. Hari ini, kami akan mempresentasikan hasil observasi kami tentang salah satu makhluk paling menakjubkan di dunia serangga.",
    technique: "Pengenalan kelompok, menunjukkan lapbook sebagai media visual.",
  },
  {
    id: "p1-3",
    timeCode: "0:20",
    timeInSeconds: 20,
    endTimeInSeconds: 40,
    speaker: PresenterId.ANDI,
    action: "Jeda 2 detik, tatap audiens dengan ekspresi penasaran.",
    speech: "Tahukah kalian... ada serangga yang bisa menyamar menjadi bunga? Bukan sekadar menyerupai — tetapi meniru setiap detail kelopak, warna, bahkan goyangan tertiup angin. Predator sekelas kadal pun tertipu.",
    technique: "Hook: pertanyaan retoris + fakta mengejutkan, jeda dramatis, ekspresi penasaran.",
  },
  {
    id: "p1-4",
    timeCode: "0:40",
    timeInSeconds: 40,
    endTimeInSeconds: 55,
    speaker: PresenterId.ANDI,
    action: "Tunjuk gambar belalang anggrek di lapbook, lalu tatap audiens lagi.",
    speech: "Serangga itu adalah belalang anggrek, atau nama ilmiahnya Hymenopus coronatus. Nah, dalam presentasi ini, kami akan mengajak kalian mengenal lebih dekat hewan yang luar biasa ini — mulai dari ciri fisiknya yang unik, perilaku berburunya yang menakjubkan, hingga perannya dalam ekosistem kita.",
    technique: "Konteks + tujuan, menunjuk lapbook sambil berbicara (prinsip tunjuk-ucapkan).",
  },
  {
    id: "p1-5",
    timeCode: "0:55",
    timeInSeconds: 55,
    endTimeInSeconds: 60,
    speaker: PresenterId.ANDI,
    action: "Tutup lapbook perlahan, beri jeda 1 detik.",
    speech: "Pertama-tama, mari kita pahami apa itu belalang anggrek.",
    technique: "Transisi ke bagian pernyataan umum, jeda sebelum topik baru.",
  },

  // Bagian 2: Pernyataan Umum (Andi)
  {
    id: "p2-1",
    timeCode: "1:00",
    timeInSeconds: 60,
    endTimeInSeconds: 85,
    speaker: PresenterId.ANDI,
    action: "Buka lapbook, buka mini-book di area utama, tunjuk halaman pertama.",
    speech: "Belalang anggrek adalah serangga predator yang tergolong dalam ordo Mantodea, famili Hymenopodidae. Hewan ini dikenal karena kemampuan mimikrinya — yaitu meniru tampilan bunga anggrek untuk menipu mangsanya. Jadi, dia bukan hanya menyerupai bunga, tapi benar-benar berdandan menjadi bunga!",
    technique: "Bahasa lisan: istilah teknis dijelaskan ulang (mimikri = meniru tampilan), analogi sederhana.",
  },
  {
    id: "p2-2",
    timeCode: "1:25",
    timeInSeconds: 85,
    endTimeInSeconds: 105,
    speaker: PresenterId.ANDI,
    action: "Buka halaman kedua mini-book, tunjuk gambar klasifikasi.",
    speech: "Secara klasifikasi, belalang anggrek berkerabat dekat dengan belalang sembah atau mantis. Bedanya, belalang anggrek hidup di bunga, sementara belalang sembah hidup di dedaunan. Perbedaan habitat ini yang membentuk strategi kamuflase mereka masing-masing.",
    technique: "Perbandingan sederhana untuk memudahkan pemahaman, tunjuk gambar klasifikasi.",
  },
  {
    id: "p2-3",
    timeCode: "1:45",
    timeInSeconds: 105,
    endTimeInSeconds: 112,
    speaker: PresenterId.ANDI,
    action: "Tutup mini-book perlahan, hadapkan tubuh ke audiens, senyum.",
    speech: "Nah, itu gambaran umum tentang belalang anggrek. Sekarang, mari kita lihat lebih detail ciri fisiknya yang sangat menarik. Saya akan mengoper presentasi ke Sinta yang akan menjelaskan bagian ini.",
    technique: "Ringkasan singkat + transisi ke presenter berikutnya, formula: ringkasan + pengantar + perkenalan.",
  },
  {
    id: "p2-4",
    timeCode: "1:52",
    timeInSeconds: 112,
    endTimeInSeconds: 115,
    speaker: PresenterId.ANDI,
    action: "Langkah mundur, serahkan lapbook ke Sinta dengan dua tangan.",
    speech: "Sinta, silakan.",
    technique: "Sopan menyerahkan media, senyum.",
  },

  // Bagian 3: Deskripsi Ciri Fisik (Sinta)
  {
    id: "p3-1",
    timeCode: "1:55",
    timeInSeconds: 115,
    endTimeInSeconds: 125,
    speaker: PresenterId.SINTA,
    action: "Terima lapbook dari Andi, senyum, tatap audiens.",
    speech: "Terima kasih, Andi. Selamat pagi, teman-teman. Mari kita lihat lebih dekat penampilan belalang anggrek yang luar biasa ini.",
    technique: "Ucapan terima kasih ke presenter sebelumnya, perkenalan singkat.",
  },
  {
    id: "p3-2",
    timeCode: "2:05",
    timeInSeconds: 125,
    endTimeInSeconds: 145,
    speaker: PresenterId.SINTA,
    action: "Tunjuk area kiri atas lapbook, buka flap pertama perlahan.",
    speech: "Pertanyaannya: apa yang membuat belalang anggrek terlihat seperti bunga? Jawabannya ada di warna tubuhnya. Belalang anggrek memiliki warna merah muda, putih, atau kuning pucat yang sangat mirip dengan kelopak bunga anggrek.",
    technique: "Teknik buka flap dengan pertanyaan, jeda untuk membangun rasa ingin tahu, prinsip tunjuk-ucapkan.",
  },
  {
    id: "p3-3",
    timeCode: "2:25",
    timeInSeconds: 145,
    endTimeInSeconds: 160,
    speaker: PresenterId.SINTA,
    action: "Buka flap kedua, tunjuk gambar anatomi.",
    speech: "Selain warna, bentuk tubuhnya juga menyerupai kelopak bunga. Kaki dan sayapnya melebar dengan tonjolan-tonjolan yang mirip kelopak. Bahkan perutnya pun berbentuk seperti tangkai bunga.",
    technique: "Penjelasan visual, merujuk pada gambar anatomi di flap.",
  },
  {
    id: "p3-4",
    timeCode: "2:40",
    timeInSeconds: 160,
    endTimeInSeconds: 185,
    speaker: PresenterId.SINTA,
    action: "Buka jendela (window) di area kanan atas, satu per satu.",
    speech: "Sekarang, mari kita intip bagian-bagian tubuhnya. Di bagian kepala... terdapat mata majemuk yang sangat peka, mampu mendeteksi gerakan mangsa dari jarak jauh. Di bagian toraks... terdapat dua sayap dan kaki raptorial yang berbentuk seperti gunting.",
    technique: "Membuka window satu per satu, prinsip tunjuk-ucapkan, jeda antar pembukaan window.",
  },
  {
    id: "p3-5",
    timeCode: "3:05",
    timeInSeconds: 185,
    endTimeInSeconds: 200,
    speaker: PresenterId.SINTA,
    action: "Tunjuk jendela ketiga yang menunjukkan kaki raptorial.",
    speech: "Nah, kaki raptorial ini senjata utamanya. Kaki ini dilengkapi duri-duri tajam yang digunakan untuk mencengkeram mangsa dalam waktu hanya satu per dua puluh detik. Cepat banget, kan?",
    technique: "Data spesifik dengan penekanan lisan, bahasa santai untuk memudahkan pemahaman.",
  },
  {
    id: "p3-6",
    timeCode: "3:20",
    timeInSeconds: 200,
    endTimeInSeconds: 210,
    speaker: PresenterId.SINTA,
    action: "Tutup jendela perlahan, hadapkan tubuh ke audiens.",
    speech: "Jadi, ciri fisik belalang anggrek sangat dirancang untuk dua tujuan: menyerupai bunga agar tidak terdeteksi mangsa, dan memiliki senjata mematikan untuk menangkap mangsa. Sekarang, bagaimana cara belalang anggrek menggunakan kemampuan ini di alam liar? Saya akan mengoper ke Rina untuk menjelaskan perilaku dan habitatnya.",
    technique: "Rangkuman ciri fisik, transisi ke presenter berikutnya.",
  },
  {
    id: "p3-7",
    timeCode: "3:30",
    timeInSeconds: 210,
    endTimeInSeconds: 213,
    speaker: PresenterId.SINTA,
    action: "Serahkan lapbook ke Rina.",
    speech: "Rina, silakan.",
    technique: "Penyerahan media yang sopan.",
  },

  // Bagian 4: Deskripsi Perilaku & Habitat (Rina)
  {
    id: "p4-1",
    timeCode: "3:33",
    timeInSeconds: 213,
    endTimeInSeconds: 223,
    speaker: PresenterId.RINA,
    action: "Terima lapbook dari Sinta, senyum ke audiens.",
    speech: "Terima kasih, Sinta. Teman-teman, tadi Sinta sudah menjelaskan senjata belalang anggrek. Sekarang, mari kita lihat bagaimana senjata itu digunakan di alam liar.",
    technique: "Ucapan terima kasih, menghubungkan dengan bagian sebelumnya.",
  },
  {
    id: "p4-2",
    timeCode: "3:43",
    timeInSeconds: 223,
    endTimeInSeconds: 255,
    speaker: PresenterId.RINA,
    action: "Tarik accordion di area kiri tengah perlahan.",
    speech: "Proses berburu belalang anggrek dimulai ketika dia memilih posisi di atas bunga anggrek yang sesungguhnya. Dia diam sempurna, menyerupai kelopak bunga. Ketika serangga lain datang untuk mengisap nektar, belalang anggrek tidak bergerak sedikit pun. Dia menunggu... dan menunggu... Lalu, saat mangsanya berada dalam jangkauan... WHUSH! Kaki raptorialnya meluncur dalam waktu satu per dua puluh detik!",
    technique: "Storytelling dramatis, tarik accordion bertahap, jeda dramatis, onomatope ('WHUSH') untuk efek suara.",
  },
  {
    id: "p4-3",
    timeCode: "4:15",
    timeInSeconds: 255,
    endTimeInSeconds: 280,
    speaker: PresenterId.RINA,
    action: "Putar wheel di area kanan tengah secara perlahan.",
    speech: "Mangsa belalang anggrek beragam. Mari kita lihat... Kupu-kupu, ngengat, lalat, lebah, bahkan kadal kecil dan katak kecil sekalipun bisa jadi sasarannya. Tingkat keberhasilan predasinya mencapai sembilan puluh persen. Saya ulangi: sembilan puluh persen! Ini adalah salah satu tingkat keberhasilan tertinggi di dunia serangga predator.",
    technique: "Wheel untuk klasifikasi, pengulangan strategis untuk penekanan data, intonasi naik pada angka penting.",
  },
  {
    id: "p4-4",
    timeCode: "4:40",
    timeInSeconds: 280,
    endTimeInSeconds: 305,
    speaker: PresenterId.RINA,
    action: "Keluarkan kartu dari pocket di area kiri bawah, satu per satu.",
    speech: "Di mana belalang anggrek ini hidup? Hutan tropis Asia Tenggara, termasuk Indonesia. Dia menyukai daerah dengan banyak bunga anggrek, terutama di ketinggian nol sampai lima ratus meter di atas permukaan laut. Sayangnya, habitatnya kini semakin terancam akibat deforestasi dan perdagangan hewan peliharaan ilegal.",
    technique: "Mengeluarkan kartu satu per satu dari pocket, bahasa bervariasi dari informatif ke emosional.",
  },
  {
    id: "p4-5",
    timeCode: "5:05",
    timeInSeconds: 305,
    endTimeInSeconds: 315,
    speaker: PresenterId.RINA,
    action: "Masukkan kartu kembali ke pocket, hadapkan tubuh ke audiens.",
    speech: "Jadi, belalang anggrek adalah pemburu yang sangat efektif dengan tingkat keberhasilan sembilan puluh persen, namun keberadaannya di alam liar kini semakin terancam. Teman-teman, inilah yang membuat observasi dan pelestarian hewan ini sangat penting. Sekarang, Budi akan merangkum temuan kami dan memimpin sesi tanya jawab.",
    technique: "Rangkuman + isu signifikan, transisi ke presenter penutup.",
  },
  {
    id: "p4-6",
    timeCode: "5:15",
    timeInSeconds: 315,
    endTimeInSeconds: 318,
    speaker: PresenterId.RINA,
    action: "Serahkan lapbook ke Budi.",
    speech: "Budi, silakan.",
    technique: "Penyerahan media yang sopan.",
  },

  // Bagian 5: Kesimpulan (Budi)
  {
    id: "p5-1",
    timeCode: "5:18",
    timeInSeconds: 318,
    endTimeInSeconds: 325,
    speaker: PresenterId.BUDI,
    action: "Terima lapbook dari Rina, tatap audiens dengan ekspresi serius.",
    speech: "Terima kasih, Rina. Teman-teman, izinkan saya merangkum temuan utama observasi kami.",
    technique: "Ucapan terima kasih, ekspresi serius sesuai konteks kesimpulan.",
  },
  {
    id: "p5-2",
    timeCode: "5:25",
    timeInSeconds: 325,
    endTimeInSeconds: 350,
    speaker: PresenterId.BUDI,
    action: "Buka flap besar di area tengah bawah, tunjuk ringkasan tertulis.",
    speech: "Pertama, belalang anggrek adalah serangga predator dengan kemampuan mimikri luar biasa yang menyerupai bunga anggrek. Kedua, kaki raptorialnya mampu menangkap mangsa dalam satu per dua puluh detik dengan tingkat keberhasilan sembilan puluh persen. Ketiga, habitatnya di hutan tropis Asia Tenggara kini semakin terancam.",
    technique: "Merangkum dalam poin-poin bernomor, membuka flap ringkasan, prinsip tunjuk-ucapkan.",
  },
  {
    id: "p5-3",
    timeCode: "5:50",
    timeInSeconds: 350,
    endTimeInSeconds: 365,
    speaker: PresenterId.BUDI,
    action: "Tutup lapbook perlahan, tatap audiens dengan ekspresi tulus.",
    speech: "Pesan yang ingin kami sampaikan: belalang anggrek ini membuktikan bawah alam memiliki strategi pertahanan diri yang luar biasa. Namun, strategi itu tidak bisa melindungi mereka dari ancaman terbesar — yaitu aktivitas manusia. Semoga observasi kami bisa meningkatkan kesadaran kita untuk melestarikan kekayaan alam Indonesia.",
    technique: "Pesan penutup yang bermakna, menghubungkan temuan dengan isu nyata, intonasi menurun untuk kesan tegas.",
  },
  {
    id: "p5-4",
    timeCode: "365", // 6:05
    timeInSeconds: 365,
    endTimeInSeconds: 380,
    speaker: PresenterId.BUDI,
    action: "Senyum hangat ke audiens.",
    speech: "Demikian presentasi dari Kelompok 3. Kami menyadari masih banyak kekurangan dan sangat mengharapkan masukan dari Bapak/Ibu guru dan teman-teman. Sekarang, kami membuka sesi tanya jawab. Silakan bagi yang ingin bertanya.",
    technique: "Kesantunan: mengakui kekurangan, mengundang pertanyaan, senyum hangat.",
  },

  // Bagian 7: Penutup (Budi & Kelompok)
  {
    id: "p7-1",
    timeCode: "8:50",
    timeInSeconds: 530,
    endTimeInSeconds: 540,
    speaker: PresenterId.BUDI,
    action: "Keempat anggota kelompok berdiri berjajar, Budi di tengah.",
    speech: "Baik, kami rasa cukup untuk sesi tanya jawabnya. Terima kasih banyak untuk pertanyaan-pertanyaannya — sangat memperkaya diskusi kita.",
    technique: "Menutup sesi Q&A dengan apresiasi, keempat anggota berdiri bersama.",
  },
  {
    id: "p7-2",
    timeCode: "9:00",
    timeInSeconds: 540,
    endTimeInSeconds: 555,
    speaker: PresenterId.BUDI,
    action: "Keempat anggota membungkukkan badan bersamaan.",
    speech: "Sekali lagi, demikian presentasi dari Kelompok 3 tentang belalang anggrek. Kami menyadari masih ada banyak kekurangan dan akan terus belajar untuk memperbaikinya. Terima kasih atas perhatian Bapak/Ibu guru dan teman-teman sekalian.",
    technique: "Penutup yang santun, mengakui kekurangan, mengucapkan terima kasih, membungkuk bersama.",
  },
  {
    id: "p7-3",
    timeCode: "9:15",
    timeInSeconds: 555,
    endTimeInSeconds: 565,
    speaker: PresenterId.BUDI,
    action: "Senyum, angguk ke audiens.",
    speech: "Wassalamualaikum warahmatullahi wabarakatuh.",
    technique: "Salam penutup yang santun, konsisten dengan pembukaan.",
  }
];

export const staticQAItems: QAItem[] = [
  {
    id: "q-1",
    question: "Apakah belalang anggrek berbahaya bagi manusia?",
    category: "Bahaya & Interaksi Manusia",
    responder: PresenterId.ANDI,
    response: "Pertanyaan yang bagus! Belalang anggrek sama sekali tidak berbahaya bagi manusia. Kaki raptorialnya memang tajam, tapi ukurannya terlalu kecil untuk melukai kulit manusia. Justru, keberadaannya di suatu ekosistem menandakan keseimbangan lingkungan yang baik.",
    techniques: "Apresiasi ('Pertanyaan yang bagus!'), Klarifikasi (tidak bahaya bagi manusia & ukuran kecil), Tanggapan berbasis ekosistem (indikator keseimbangan lingkungan).",
  },
  {
    id: "q-2",
    question: "Bagaimana cara belalang anggrek mengubah warna tubuhnya?",
    category: "Proses Biologis",
    responder: PresenterId.SINTA,
    response: "Terima kasih atas pertanyaannya. Jujur, observasi kami tidak mencakup proses perubahan warna secara detail. Namun, dari literatur yang kami baca, belalang anggrek tidak mengubah warna secara aktif seperti bunglon. Warna tubuhnya terbentuk melalui proses molting atau ekdisis, yaitu pergantian kulit, dan dipengaruhi oleh warna lingkungan tempat dia tumbuh.",
    techniques: "Apresiasi, Kejujuran atas keterbatasan riset ('Jujur, observasi kami tidak mencakup...'), Jawaban berbasis referensi literatur ilmiah.",
  },
  {
    id: "q-3",
    question: "Kalau belalang anggrek hidupnya di bunga, berarti dia membantu penyerbukan, kan?",
    category: "Peran Ekologis",
    responder: PresenterId.RINA,
    response: "Wah, pertanyaan yang menarik! Sebenarnya, belalang anggrek tidak membantu penyerbukan karena dia tidak berpindah dari bunga ke bunga untuk mencari nektar — dia justru menunggu di satu bunga untuk menangkap serangga penyerbuk yang datang. Jadi dalam beberapa kasus, belalang anggrek justru mengganggu proses penyerbukan. Tapi perannya sebagai predator juga penting untuk mengendalikan populasi serangga tertentu.",
    techniques: "Apresiasi, Klarifikasi berbasis data (predator penyergap pasif, bukan polinator), Keseimbangan perspektif (peran pengendalian populasi).",
  },
  {
    id: "q-4",
    question: "Menurut kelompokmu, apa yang harus dilakukan untuk melindungi belalang anggrek?",
    category: "Upaya Konservasi",
    responder: PresenterId.BUDI,
    response: "Terima kasih, pertanyaan yang sangat penting. Berdasarkan observasi dan referensi kami, ada beberapa langkah yang bisa dilakukan: pertama, menjaga kelestarian hutan tropis sebagai habitat alaminya; kedua, menghentikan perdagangan ilegal belalang anggrek sebagai hewan peliharaan; dan ketiga, meningkatkan penelitian dan edukasi tentang spesies ini agar masyarakat lebih menyadari pentingnya peran belalang anggrek dalam ekosistem.",
    techniques: "Apresiasi, Klasifikasi rekomendasi multi-level (konkret dari mikro hingga makro berbasis data).",
  },
  {
    id: "q-5",
    question: "Apa perbedaan belalang anggrek dengan belalang sembah biasa?",
    category: "Komparasi Spesies",
    responder: PresenterId.BUDI,
    response: "Terima kasih atas pertanyaannya. Pertanyaan ini sebenarnya agak di luar fokus observasi kami, tapi saya akan coba jawab singkat. Perbedaan utamanya ada di strategi kamuflase: belalang anggrek meniru bunga, sedangkan belalang sembah meniru dedaunan atau ranting. Tentang detail perbedaannya, mungkin bisa kita diskusikan lebih lanjut setelah presentasi.",
    techniques: "Sopan mengarahkan fokus agenda, Penjelasan singkat perbedaan inti (bunga vs daun), Penawaran diskusi lanjutan di luar sesi formal.",
  }
];

export const lapbookComponents: LapbookComponent[] = [
  {
    id: "cover",
    name: "Sampul Lapbook (Closed State)",
    type: "cover",
    description: "Cover visual bergaya lipat dua (gatefold cover) yang meniru kelopak bunga anggrek hutan.",
    presenter: PresenterId.ANDI,
    techniqueTip: "Efek Keterkejutan (Surprise Effect)",
    realLifeCrafting: "Gunakan kertas tebal bermotif kelopak anggrek yang saling bertumpuk di tengah ketika ditutup, sehingga memerlukan aksi 'membuka tirai' di detik pertama.",
  },
  {
    id: "banner",
    name: "Banner Judul Utama",
    type: "banner",
    description: "Judul utama presentasi 'Klasifikasi & Observasi Belalang Anggrek (Hymenopus coronatus)'.",
    presenter: PresenterId.ANDI,
    techniqueTip: "Prinsip Tunjuk-Ucapkan (Point & Speak)",
    realLifeCrafting: "Dibuat menonjol di bagian tengah atas, disorot dengan pita 3D agar audiens dari kejauhan bisa langsung membaca fokus utama presentasi.",
  },
  {
    id: "minibook",
    name: "Mini-Book Klasifikasi",
    type: "minibook",
    description: "Buku mini lipat 4 halaman yang merangkum ordo Mantodea, famili Hymenopodidae, dan hubungan kekerabatannya.",
    presenter: PresenterId.ANDI,
    techniqueTip: "Visual Disclosure Bertahap",
    realLifeCrafting: "Buku berukuran 10x10cm yang dijilid spiral mandiri di dalam lapbook, ditempel di panel kiri sehingga presenter bisa membuka halaman demi halaman sesuai ritme klasifikasi.",
  },
  {
    id: "flap_color",
    name: "Flap Warna Kamuflase",
    type: "flap",
    description: "Katup lipat ke atas berisi sampel warna primer belalang anggrek: Merah Muda, Putih, dan Kuning Kelopak.",
    presenter: PresenterId.SINTA,
    techniqueTip: "Curiosity Flaps (Membuka setelah bertanya)",
    realLifeCrafting: "Gunakan kertas lipat sewarna kelopak bunga asli, tuliskan teks penjelasan di sisi bawah katup sehingga katup harus diangkat ke atas untuk dibaca.",
  },
  {
    id: "windows_anatomy",
    name: "Jendela Anatomi (Kepala, Toraks, Kaki)",
    type: "window",
    description: "Tiga daun jendela lipat samping bergambar anatomi mikro: Mata Majemuk, Toraks Bersayap, dan Kaki Raptorial.",
    presenter: PresenterId.SINTA,
    techniqueTip: "Interaksi Searah Jam (Clockwise reveal)",
    realLifeCrafting: "Dipotong menggunakan silet cutter membentuk jendela lipat ganda dengan engsel kertas. Menyembunyikan gambar duri tajam kaki raptorial di balik daun jendela ketiga.",
  },
  {
    id: "accordion_hunt",
    name: "Akordion Storytelling Berburu",
    type: "accordion",
    description: "Klip lipat akordion panjang (zig-zag) yang menggambarkan fase berburu (Bersiap - Menunggu - Meluncur - WHUSH!).",
    presenter: PresenterId.RINA,
    techniqueTip: "Ketegangan Sinematik (Cinematic build-up)",
    realLifeCrafting: "Kertas panjang dilipat berulang gaya kipas (zig-zag). Setiap kali ditarik satu lipatan, presenter menceritakan fase penyergapan 1/20 detik.",
  },
  {
    id: "wheel_prey",
    name: "Roda Mangsa Putar (Prey Wheel)",
    type: "wheel",
    description: "Roda berputar yang memperlihatkan presentase mangsa dan jenis serangga (kupu-kupu, lalat, katak kecil). Ditulis angka keberhasilan 90% di pusat roda.",
    presenter: PresenterId.RINA,
    techniqueTip: "Klasifikasi Interaktif",
    realLifeCrafting: "Dibuat dari dua lingkaran karton bertingkat yang dihubungkan dengan paku belah (brad paper fastener). Lingkaran atas diberi lubang intip untuk menunjukkan gambar mangsa seiring berputar.",
  },
  {
    id: "pocket_habitat",
    name: "Kantong Kartu Habitat (Habitat Pocket)",
    type: "pocket",
    description: "Kantong kain/kertas bermotif belantara berisi 3 buah kartu tebal: Kartu Geografis, Kartu Ketinggian (0-500mdpl), dan Kartu Ancaman Lingkungan.",
    presenter: PresenterId.RINA,
    techniqueTip: "Tactile Retrieval (Sentuhan langsung)",
    realLifeCrafting: "Saku karton tebal berperekat yang kokoh. Kartu ditarik keluar satu per satu menggunakan benang sutra pink yang menyerupai sulur anggrek.",
  },
  {
    id: "recap_summary",
    name: "Katup Ringkasan Besar",
    type: "recap",
    description: "Flap penutup besar di bagian bawah tengah berisi 3 kesimpulan tertulis yang dirangkum rapi dalam bentuk poin-poin tebal.",
    presenter: PresenterId.BUDI,
    techniqueTip: "Pendaratan Informasi (Information Landing)",
    realLifeCrafting: "Flap lipatan besar ke bawah yang menyelimuti seluruh materi akhir kelompok 3. Bertuliskan ringkasan dengan spidol hitam kontras tinggi agar terbaca dari jarak 3 meter.",
  }
];

export const presentationTips = [
  {
    title: "Hook (Pembuka Menarik)",
    description: "Andi membuka dengan pertanyaan retoris tentang serangga menyamar jadi bunga + fakta kadal tertipu.",
    why: "Membangun rasa ingin tahu sejak detik pertama; audiens langsung terlibat dan ingin tahu jawabannya.",
  },
  {
    title: "Prinsip Tunjuk-Ucapkan",
    description: "Setiap kali presenter menunjuk komponen lapbook, mereka juga menjelaskannya secara lisan.",
    why: "Memastikan audiens yang duduk jauh tetap memahami apa yang ditunjuk; menggabungkan visual dan verbal.",
  },
  {
    title: "Jeda Dramatis",
    description: "Rina jeda 3 detik saat mendeskripsikan proses berburu sebelum mengucapkan 'WHUSH!'.",
    why: "Membangun ketegangan; memberi waktu audiens membayangkan suasana; membuat momen klimaks lebih berdampak.",
  },
  {
    title: "Buka Komponen Bertahap",
    description: "Sinta membuka jendela satu per satu; Rina mengeluarkan kartu habitat satu per satu.",
    why: "Setiap pembukaan menciptakan momen kejutan baru; audiens tidak dibanjiri informasi sekaligus.",
  },
  {
    title: "Pengulangan Strategis",
    description: "Rina mengulang persentase 'sembilan puluh persen' dengan penekanan khusus.",
    why: "Data penting perlu ditekankan agar audiens mengingat daya sergap predator yang luar biasa ini.",
  },
  {
    title: "Formula A-C-T dalam Q&A",
    description: "Setiap jawaban diawali Apresiasi, diikuti Clarification/Data, dan diakhiri Tanggapan/Rekomendasi.",
    why: "Menunjukkan kesantunan tinggi, memperjelas keaslian riset, dan memberikan penutupan solusi.",
  },
  {
    title: "Kejujuran atas Keterbatasan",
    description: "Sinta mengakui bila observasi tidak mencakup proses molting warna mendalam, lalu merujuk literatur.",
    why: "Mencegah larping/mengarang bebas, meningkatkan kredibilitas kelompok, dan membuka ruang belajar mandiri.",
  },
];
